In [1]:
import pandas as pd
import openpyxl

In [18]:
df_raw = pd.read_excel(r'H:\Python\3_Etapa\Atividade_3\Tabela_3_Areas_gerais_de_formacao_na_graduacao.xlsx', header=2)

In [22]:
df_raw

,Unnamed: 0,Total,Homens,Mulheres,Total.1,Homens.1,Mulheres.1,Total.2,Homens.2,Mulheres.2
0,Brasil,25854291.0,10478534.0,15375757.0,4149041.0,2750422.0,1398619.0,8079707.0,1677985.0,6401723.0
1,Norte,1525166.0,590558.0,934609.0,209657.0,133055.0,76601.0,599785.0,141169.0,458616.0
2,Nordeste,4748933.0,1744994.0,3003939.0,621388.0,389993.0,231395.0,1822087.0,363905.0,1458181.0
3,Sudeste,12828829.0,5391638.0,7437191.0,2328122.0,1588874.0,739247.0,3652397.0,768288.0,2884108.0
4,Sul,4338861.0,1768855.0,2570005.0,662916.0,427372.0,235543.0,1256291.0,248574.0,1007718.0
5,Centro-Oeste,2412502.0,982489.0,1430013.0,326959.0,211124.0,115834.0,749148.0,156048.0,593101.0
6,Rondônia,164632.0,62766.0,101866.0,20538.0,11863.0,8675.0,63584.0,13963.0,49622.0
7,Acre,84300.0,33291.0,51009.0,10364.0,6237.0,4128.0,33379.0,9121.0,24258.0
8,Amazonas,342566.0,141059.0,201507.0,52669.0,34749.0,17919.0,121988.0,30738.0,91249.0
9,Roraima,67045.0,25585.0,41460.0,8016.0,4958.0,3057.0,23977.0,5880.0,18098.0
10,Pará,601096.0,229285.0,371811.0,86691.0,55481.0,31211.0,248397.0,58128.0,190270.0
11,Amapá,89191.0,35085.0,54106.0,11349.0,7464.0,3885.0,36754.0,9794.0,26960.0
12,Tocantins,176336.0,63485.0,112851.0,20028.0,12304.0,7724.0,71705.0,13548.0,58158.0
13,Maranhão,468681.0,161352.0,307329.0,55068.0,33820.0,21248.0,206222.0,40667.0,165555.0
14,Piauí,304955.0,108371.0,196584.0,37135.0,21668.0,15467.0,128416.0,25959.0,102457.0
15,Ceará,759303.0,285013.0,474290.0,99062.0,63935.0,35126.0,294578.0,64582.0,229996.0
16,Rio Grande do Norte,339913.0,131178.0,208735.0,46857.0,30398.0,16459.0,135434.0,28273.0,107161.0
17,Paraíba,390742.0,147221.0,243521.0,52223.0,33369.0,18855.0,150862.0,30025.0,120837.0
18,Pernambuco,852481.0,321587.0,530893.0,120260.0,73253.0,47007.0,281695.0,57333.0,224362.0
19,Alagoas,267996.0,98462.0,169534.0,33596.0,21398.0,12198.0,106971.0,20060.0,86911.0
20,Sergipe,218255.0,80608.0,137646.0,29020.0,17596.0,11422.0,83176.0,16801.0,66376.0
21,Bahia,1146608.0,411202.0,735406.0,148167.0,94556.0,53612.0,434735.0,80208.0,354528.0
22,Minas Gerais,2615434.0,1031532.0,1583902.0,452258.0,291778.0,160479.0,832482.0,157960.0,674521.0
23,Espírito Santo,491101.0,193756.0,297344.0,75667.0,49648.0,26018.0,161332.0,29788.0,131544.0
24,Rio de Janeiro,2243707.0,942645.0,1301062.0,406529.0,265723.0,140805.0,612263.0,145864.0,466399.0
25,São Paulo,7478587.0,3223705.0,4254883.0,1393668.0,981724.0,411944.0,2046321.0,434677.0,1611645.0
26,Paraná,1687930.0,695425.0,992505.0,255635.0,166579.0,89056.0,501471.0,98191.0,403280.0
27,Santa Catarina,1162515.0,489557.0,672958.0,185742.0,126554.0,59188.0,333537.0,67571.0,265964.0
28,Rio Grande do Sul,1488416.0,583873.0,904542.0,221541.0,134240.0,87300.0,421284.0,82812.0,338472.0
29,Mato Grosso do Sul,366249.0,145341.0,220908.0,46340.0,28241.0,18100.0,128352.0,26911.0,101443.0
30,Mato Grosso,450264.0,173267.0,276997.0,56776.0,33307.0,23468.0,141121.0,27052.0,114069.0
31,Goiás,879270.0,350828.0,528443.0,116867.0,74711.0,42156.0,288616.0,56564.0,232052.0
32,Distrito Federal,716719.0,313054.0,403665.0,106976.0,74866.0,32109.0,191061.0,45521.0,145538.0
33,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df_geral = df_raw.iloc[0:33,0:4]

In [45]:
df_geral = df_geral.rename(columns={"Unnamed: 0": "Regiao"})

In [47]:
df_geral

                 Regiao       Total      Homens    Mulheres
0                Brasil  25854291.0  10478534.0  15375757.0
1                 Norte   1525166.0    590558.0    934609.0
2              Nordeste   4748933.0   1744994.0   3003939.0
3               Sudeste  12828829.0   5391638.0   7437191.0
4                   Sul   4338861.0   1768855.0   2570005.0
5          Centro-Oeste   2412502.0    982489.0   1430013.0
6              Rondônia    164632.0     62766.0    101866.0
7                  Acre     84300.0     33291.0     51009.0
8              Amazonas    342566.0    141059.0    201507.0
9               Roraima     67045.0     25585.0     41460.0
10                 Pará    601096.0    229285.0    371811.0
11                Amapá     89191.0     35085.0     54106.0
12            Tocantins    176336.0     63485.0    112851.0
13             Maranhão    468681.0    161352.0    307329.0
14                Piauí    304955.0    108371.0    196584.0
15                Ceará    759303.0    285013.0    474290.0
16  Rio Grande do Norte    339913.0    131178.0    208735.0
17              Paraíba    390742.0    147221.0    243521.0
18           Pernambuco    852481.0    321587.0    530893.0
19              Alagoas    267996.0     98462.0    169534.0
20              Sergipe    218255.0     80608.0    137646.0
21                Bahia   1146608.0    411202.0    735406.0
22         Minas Gerais   2615434.0   1031532.0   1583902.0
23       Espírito Santo    491101.0    193756.0    297344.0
24       Rio de Janeiro   2243707.0    942645.0   1301062.0
25            São Paulo   7478587.0   3223705.0   4254883.0
26               Paraná   1687930.0    695425.0    992505.0
27       Santa Catarina   1162515.0    489557.0    672958.0
28    Rio Grande do Sul   1488416.0    583873.0    904542.0
29   Mato Grosso do Sul    366249.0    145341.0    220908.0
30          Mato Grosso    450264.0    173267.0    276997.0
31                Goiás    879270.0    350828.0    528443.0
32     Distrito Federal    716719.0    313054.0    403665.0

In [11]:
df_geral.to_excel(r"H:\Python\3_Etapa\Atividade_3\Tabela_3_geral.xlsx")

In [7]:
df_A = df_raw.iloc[0:33,4:7]

In [14]:
df_A = df_A.rename(columns={"Homens.1": "Homens"})

In [30]:
df_A = df_A.rename(columns={"Mulheres.1": "Mulheres"})

In [31]:
df_A = df_A.rename(columns={"Total.1": "Total"})

In [32]:
df_A

        Total     Homens   Mulheres
0   4149041.0  2750422.0  1398619.0
1    209657.0   133055.0    76601.0
2    621388.0   389993.0   231395.0
3   2328122.0  1588874.0   739247.0
4    662916.0   427372.0   235543.0
5    326959.0   211124.0   115834.0
6     20538.0    11863.0     8675.0
7     10364.0     6237.0     4128.0
8     52669.0    34749.0    17919.0
9      8016.0     4958.0     3057.0
10    86691.0    55481.0    31211.0
11    11349.0     7464.0     3885.0
12    20028.0    12304.0     7724.0
13    55068.0    33820.0    21248.0
14    37135.0    21668.0    15467.0
15    99062.0    63935.0    35126.0
16    46857.0    30398.0    16459.0
17    52223.0    33369.0    18855.0
18   120260.0    73253.0    47007.0
19    33596.0    21398.0    12198.0
20    29020.0    17596.0    11422.0
21   148167.0    94556.0    53612.0
22   452258.0   291778.0   160479.0
23    75667.0    49648.0    26018.0
24   406529.0   265723.0   140805.0
25  1393668.0   981724.0   411944.0
26   255635.0   166579.0    89056.0
27   185742.0   126554.0    59188.0
28   221541.0   134240.0    87300.0
29    46340.0    28241.0    18100.0
30    56776.0    33307.0    23468.0
31   116867.0    74711.0    42156.0
32   106976.0    74866.0    32109.0

In [12]:
df_A.to_excel(r"H:\Python\3_Etapa\Atividade_3\Tabela_3_A.xlsx")

In [9]:
df_B = df_raw.iloc[0:33,7:10]

In [33]:
df_B = df_B.rename(columns={"Homens.2": "Homens"})

In [34]:
df_B = df_B.rename(columns={"Mulheres.2": "Mulheres"})

In [35]:
df_B = df_B.rename(columns={"Total.2": "Total"})

In [36]:
df_B

        Total     Homens   Mulheres
0   8079707.0  1677985.0  6401723.0
1    599785.0   141169.0   458616.0
2   1822087.0   363905.0  1458181.0
3   3652397.0   768288.0  2884108.0
4   1256291.0   248574.0  1007718.0
5    749148.0   156048.0   593101.0
6     63584.0    13963.0    49622.0
7     33379.0     9121.0    24258.0
8    121988.0    30738.0    91249.0
9     23977.0     5880.0    18098.0
10   248397.0    58128.0   190270.0
11    36754.0     9794.0    26960.0
12    71705.0    13548.0    58158.0
13   206222.0    40667.0   165555.0
14   128416.0    25959.0   102457.0
15   294578.0    64582.0   229996.0
16   135434.0    28273.0   107161.0
17   150862.0    30025.0   120837.0
18   281695.0    57333.0   224362.0
19   106971.0    20060.0    86911.0
20    83176.0    16801.0    66376.0
21   434735.0    80208.0   354528.0
22   832482.0   157960.0   674521.0
23   161332.0    29788.0   131544.0
24   612263.0   145864.0   466399.0
25  2046321.0   434677.0  1611645.0
26   501471.0    98191.0   403280.0
27   333537.0    67571.0   265964.0
28   421284.0    82812.0   338472.0
29   128352.0    26911.0   101443.0
30   141121.0    27052.0   114069.0
31   288616.0    56564.0   232052.0
32   191061.0    45521.0   145538.0

In [13]:
df_B.to_excel(r"H:\Python\3_Etapa\Atividade_3\Tabela_3_B.xlsx")